#!/bin/sh

if [ ! -f /etc/fdns.env ]; then
	echo "DATABASE_URL=" >> /etc/fdns.env
	echo "METRICS_URL=" >> etc/fdns.env
fi

systemctl is-active --quiet dns-server && systemctl restart dns-server || true
