#!/bin/sh

if [ ! -f /etc/hostsdottxt.env ]; then
	echo "DATABASE_URL=" >> /etc/hostsdottxt.env
	echo "METRICS_URL=" >> etc/hostsdottxt.env
fi

systemctl is-active --quiet dns-server && systemctl daemon-reload && systemctl restart dns-server || true
